PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS "Economy";
DROP TABLE IF EXISTS "GoodGroups";
DROP TABLE IF EXISTS "GoodNames";
DROP TABLE IF EXISTS "Government";
DROP TABLE IF EXISTS "Stations";
DROP TABLE IF EXISTS "Systems";
DROP TABLE IF EXISTS "prices";

CREATE TABLE IF NOT EXISTS "Economy" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
  "name" VARCHAR NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS "GoodGroups" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
  "position" INTEGER NOT NULL,
  "name" TEXT UNIQUE);

CREATE TABLE IF NOT EXISTS "GoodNames" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
  "name" TEXT NOT NULL UNIQUE,
  "legal" BOOL NOT NULL,
  "group_id" INTEGER NOT NULL,
  FOREIGN KEY(group_id) REFERENCES GoodGroups(id));

CREATE TABLE IF NOT EXISTS "Government" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
  "name" VARCHAR NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS "Stations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "system_id" INTEGER NOT NULL,
  "government_id" INTEGER NOT NULL,
  FOREIGN KEY(system_id) REFERENCES Systems(id),
  FOREIGN KEY(government_id) REFERENCES Government(id));

CREATE TABLE IF NOT EXISTS "Systems" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR NOT NULL,
  "economy_id" INTEGER NOT NULL,
  "government_id" INTEGER NOT NULL,
  "Population" INTEGER,
  FOREIGN KEY(economy_id) REFERENCES Economy(id),
  FOREIGN KEY(government_id) REFERENCES Government(id));

CREATE TABLE IF NOT EXISTS "prices" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "good_id" INTEGER NOT NULL,
  "station_id" INTEGER NOT NULL,
  "time" DATETIME NOT NULL,
  "sale_price" FLOAT,
  "buy_price" FLOAT,
  FOREIGN KEY(good_id) REFERENCES GoodNames(id),
  FOREIGN KEY(station_id) REFERENCES Stations(id));
